version: '3.8'
services:
  app:
    build: .
    container_name: cnn-container
    user: myuser
    command: uvicorn src.main:app --host 0.0.0.0 --port 4000 --reload
    ports:
      - "4000:4000"
    volumes:
      - ./src:/code/src
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:6.2-alpine
    container_name: redis
    networks:
      - app-network
    volumes:
      - redis-data:/data

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local